# Generated by Django 4.2.2 on 2024-07-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_cartitem_subtotal_alter_product_imagen1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='numero_seguimiento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
